import type { FileChangeSummary, Message } from '../types/chat';

export interface ConversationHandoffOptions {
  maxChars?: number;
  fullTranscriptThreshold?: number;
  maxGoalChars?: number;
  maxRequirementChars?: number;
  maxDecisionChars?: number;
  maxRecentMessageChars?: number;
}

const DEFAULT_OPTIONS: Required<ConversationHandoffOptions> = {
  maxChars: 8000,
  fullTranscriptThreshold: 5200,
  maxGoalChars: 900,
  maxRequirementChars: 450,
  maxDecisionChars: 450,
  maxRecentMessageChars: 1800,
};

type Role = 'user' | 'assistant';

interface NormalizedMessage {
  role: Role;
  text: string;
  index: number;
}

/**
 * Build compact handoff context for switching agents mid-conversation.
 *
 * The algorithm is intentionally deterministic and budget-based:
 * - If the conversation is short enough, include the full transcript.
 * - If it is long, always preserve the latest user prompt and latest assistant reply.
 * - Use the remaining budget for compact context extracted from older turns.
 *
 * This function is kept separate from React/Kotlin code on purpose so the
 * compaction rules are easy to review and tweak without tracing UI state.
 */
export function buildConversationHandoffContext(
  messages: Message[],
  fileChanges: FileChangeSummary[] = [],
  options: ConversationHandoffOptions = {},
): string {
  const cfg = { ...DEFAULT_OPTIONS, ...options };
  const normalized = normalizeMessages(messages);
  if (normalized.length === 0) return '';

  const fullTranscript = renderTranscript(normalized);
  if (fullTranscript.length <= cfg.fullTranscriptThreshold && fullTranscript.length <= cfg.maxChars) {
    return wrapTransfer([
      section('FULL TRANSCRIPT', fullTranscript),
      section('NOTES', 'This is the complete conversation transcript because it fit within the transfer budget.'),
    ]);
  }

  const lastUser = findLastByRole(normalized, 'user');
  const lastAssistant = findLastByRole(normalized, 'assistant');
  const olderMessages = normalized.filter((msg) => msg !== lastUser && msg !== lastAssistant);

  const fileSection = formatFileChanges(fileChanges);
  const goalSection = formatGoal(normalized, cfg.maxGoalChars);
  const requirementsSection = formatSignalList(
    selectImportantOlderMessages(olderMessages, 'user'),
    cfg.maxRequirementChars,
  );
  const decisionsSection = formatSignalList(
    selectImportantOlderMessages(olderMessages, 'assistant'),
    cfg.maxDecisionChars,
  );

  const recentMessages = selectRecentMessages(normalized, lastUser, lastAssistant);
  const recentTranscript = renderTranscript(
    recentMessages.map((msg) => ({
      ...msg,
      text: truncateHeadTail(msg.text, cfg.maxRecentMessageChars),
    })),
  );

  const pieces = [
    section('GOAL', goalSection),
    section('IMPORTANT USER REQUIREMENTS', requirementsSection),
    section('IMPORTANT ASSISTANT DECISIONS', decisionsSection),
    section('FILES TO KNOW ABOUT', fileSection),
  ].filter(Boolean) as string[];

  const notes = [
    'This context was generated by the IDE plugin when switching to a new agent session.',
    'Earlier turns may be compacted or truncated to stay within budget.',
    'Prioritize the latest user message and the latest assistant reply over older context.',
  ].join(' ');

  const mandatoryRecent = [
    section('RECENT TRANSCRIPT', recentTranscript),
    section('NOTES', notes),
  ];

  const fixedOverhead = wrapTransfer([...mandatoryRecent]).length - mandatoryRecent.join('\n\n').length;
  const recentLength = mandatoryRecent.join('\n\n').length;
  const remainingBudget = Math.max(0, cfg.maxChars - fixedOverhead - recentLength);
  const compactContext = fitSectionsWithinBudget(pieces, remainingBudget);

  return wrapTransfer([...compactContext, ...mandatoryRecent]);
}

/**
 * Convert the prepared handoff summary into a plain-text prompt prefix.
 *
 * The goal here is explicitness: the next agent should clearly understand that
 * this block is transferred context from the previous session, not a fresh user
 * instruction. Keeping this formatter separate makes it easy to tweak the
 * wording later without touching the chat/session logic.
 */
export function buildConversationHandoffPromptPrefix(handoffText: string): string {
  const normalized = normalizeText(handoffText);
  if (!normalized) return '';

  return [
    '[TRANSFERRED CONTEXT]',
    'The following block was generated by the IDE plugin while switching to a new agent session.',
    'Treat it as background context from the previous session, not as a new user request.',
    normalized,
    '[/TRANSFERRED CONTEXT]',
    '',
    '[USER REQUEST]',
  ].join('\n\n');
}

function normalizeMessages(messages: Message[]): NormalizedMessage[] {
  return messages
    .map((message, index) => {
      const text = normalizeText(message.content || '');
      if (!text) return null;
      return {
        role: message.role,
        text,
        index,
      } as NormalizedMessage;
    })
    .filter((message): message is NormalizedMessage => message !== null);
}

function normalizeText(text: string): string {
  return text
    .replace(/\r\n/g, '\n')
    .replace(/\n{3,}/g, '\n\n')
    .replace(/[ \t]+\n/g, '\n')
    .trim();
}

function wrapTransfer(sections: string[]): string {
  return [
    '[PLUGIN CONTEXT TRANSFER]',
    ...sections.filter(Boolean),
    '[/PLUGIN CONTEXT TRANSFER]',
  ].join('\n\n');
}

function section(title: string, body: string): string {
  const text = normalizeText(body);
  if (!text) return '';
  return [`[${title}]`, text, `[/${title}]`].join('\n');
}

function renderTranscript(messages: NormalizedMessage[]): string {
  return messages
    .map((message) => `${message.role === 'user' ? 'User' : 'Assistant'}: ${message.text}`)
    .join('\n\n');
}

function findLastByRole(messages: NormalizedMessage[], role: Role): NormalizedMessage | null {
  for (let i = messages.length - 1; i >= 0; i--) {
    if (messages[i].role === role) return messages[i];
  }
  return null;
}

function formatGoal(messages: NormalizedMessage[], maxChars: number): string {
  const firstUser = messages.find((message) => message.role === 'user');
  return firstUser ? truncateHeadTail(firstUser.text, maxChars) : '';
}

function formatSignalList(
  messages: NormalizedMessage[],
  maxCharsPerItem: number,
): string {
  if (messages.length === 0) return '';
  return messages
    .slice(0, 4)
    .map((message) => `- ${truncateHeadTail(message.text, maxCharsPerItem)}`)
    .join('\n');
}

function formatFileChanges(fileChanges: FileChangeSummary[]): string {
  if (fileChanges.length === 0) return '';
  return fileChanges
    .slice(0, 8)
    .map((file) => {
      const changeType = file.status === 'A' ? 'added' : 'modified';
      return `- ${file.filePath} (${changeType}, +${file.additions}/-${file.deletions})`;
    })
    .join('\n');
}

function selectImportantOlderMessages(messages: NormalizedMessage[], role: Role): NormalizedMessage[] {
  return messages
    .filter((message) => message.role === role)
    .map((message) => ({ message, score: scoreMessage(message) }))
    .filter((entry) => entry.score > 0)
    .sort((left, right) => {
      if (right.score !== left.score) return right.score - left.score;
      return right.message.index - left.message.index;
    })
    .map((entry) => entry.message);
}

function scoreMessage(message: NormalizedMessage): number {
  const text = message.text.toLowerCase();
  let score = 0;

  if (message.role === 'user') {
    if (/\b(must|need|should|important|instead|don't|do not|without|keep|preserve|required)\b/.test(text)) score += 6;
    if (/\b(fix|change|implement|avoid|support|pass|send|switch)\b/.test(text)) score += 4;
  } else {
    if (/\b(fixed|changed|updated|implemented|root cause|issue|plan|next|summary|approach)\b/.test(text)) score += 6;
    if (/\b(file|session|context|agent|adapter|prompt|meta)\b/.test(text)) score += 3;
  }

  if (/@[^\s]+|[a-z]:\\|\/src\/|\.kt\b|\.ts\b|\.tsx\b|\.java\b/i.test(message.text)) score += 3;
  if (text.length > 40) score += 1;

  return score;
}

function selectRecentMessages(
  messages: NormalizedMessage[],
  lastUser: NormalizedMessage | null,
  lastAssistant: NormalizedMessage | null,
): NormalizedMessage[] {
  const selected = new Map<number, NormalizedMessage>();

  if (lastUser) selected.set(lastUser.index, lastUser);
  if (lastAssistant) selected.set(lastAssistant.index, lastAssistant);

  for (let i = messages.length - 1; i >= 0 && selected.size < 4; i--) {
    selected.set(messages[i].index, messages[i]);
  }

  return Array.from(selected.values()).sort((left, right) => left.index - right.index);
}

function fitSectionsWithinBudget(sections: string[], maxChars: number): string[] {
  if (maxChars <= 0) return [];

  const fitted: string[] = [];
  let used = 0;
  for (const current of sections) {
    if (!current) continue;
    const extra = (fitted.length > 0 ? 2 : 0) + current.length;
    if (used + extra <= maxChars) {
      fitted.push(current);
      used += extra;
      continue;
    }

    const remaining = maxChars - used - (fitted.length > 0 ? 2 : 0);
    if (remaining < 160) break;

    fitted.push(truncateHeadTail(current, remaining));
    break;
  }

  return fitted;
}

function truncateHeadTail(text: string, maxChars: number): string {
  const normalized = normalizeText(text);
  if (normalized.length <= maxChars) return normalized;
  if (maxChars <= 32) return normalized.slice(0, maxChars);

  const marker = '\n[... truncated ...]\n';
  const remaining = maxChars - marker.length;
  const head = Math.ceil(remaining * 0.6);
  const tail = Math.max(0, remaining - head);

  return `${normalized.slice(0, head)}${marker}${normalized.slice(normalized.length - tail)}`;
}
